### ISSUE TITLE
Error connecting to PostgreSQL 8.3.4 database

### ISSUE THREAD

**Issue by nescafe2002** [fknx/linqpad-postgresql-driver#1]
Test Connection: Connection successful

On expanding data connection or running query bound to connection, the following error appears:

***NpgsqlException - 42601: syntax error at or near ""TableCatalog""***

Sniffed problematic SQL query:
```sql
SELECT table_catalog "TableCatalog", table_name "TableName" 
FROM information_schema.tables 
WHERE table_type='BASE TABLE' AND table_schema='public'
```

Suggested fix:

Change this line:
```sql
SELECT table_catalog "TableCatalog", table_name "TableName"
```

Into:
```sql
SELECT table_catalog AS "TableCatalog", table_name AS "TableName"
```

Probably more files could be 'fixed' this way?

**Comment by fknx** [comment]
I've applied the fix you suggested and tested it with PostgreSQL 8.3.23 and it seems to work fine. I've release a new version (0.1.1) containing the fix.

It would be great if you could verify whether this solves your issue.

**Comment by nescafe2002** [comment]
Tested, issue is solved. Thanks.
