### ISSUE TITLE
Set default dialog button to Save instead Cancel

### ISSUE THREAD

**Issue by rornor** [fknx/linqpad-postgresql-driver#19]
After filling the fields in PG connection dialog, and pressing Enter nothing happens, because Cancel is set as default button. So I have to launch the dialog again and refill the fields then explicitly press Save button with my mouse. I think this is counterintuitive and that Enter should default to Save button when fields are completed.

**Comment by fknx** [comment]
This has been done by #24 and has been released with version `0.3.0`.
