### ISSUE TITLE
Schema support

### ISSUE THREAD

**Issue by zinark** [fknx/linqpad-postgresql-driver#21]
It is only possible to see tables in "public" schema and other schemas are not visible. I checked the source in the sql file "QueryTables.sql". It just only collect the public ones. I changed but couldn't run it again.

```
SELECT 
    table_catalog AS "TableCatalog", 
    table_name  AS "TableName",
    table_schema AS "TableSchema"
FROM information_schema.tables 
WHERE table_type='BASE TABLE' AND table_schema in (select schema_name from information_schema.schemata where schema_owner != 'postgres')
```

**Comment by marius-narbutas** [comment]
Yes, this definitely should be changed, I guess the easiest way would be just to concatenate schema name with table name (in this example using lower hyphen, but it is up to you):
```sql
SELECT table_catalog AS "TableCatalog", (table_schema || '_' || table_name) AS "TableName" 
FROM information_schema.tables 
WHERE table_type='BASE TABLE';
```
Also I think there is no good reason to filter tables by schema name.

Can it be implemented?

**Comment by BerBarBat** [comment]
I would like to know more about working with schemes with the postgresql driver for linqpad. As explained in the previous post only the public outline is visible.

**Comment by teejay-87** [comment]
See here: https://github.com/teejay-87/linqpad-postgresql-driver

I submitted a pull request though.

**Comment by fknx** [comment]
The pull request #24 has been merged and schema support for tables is now available.
