### ISSUE TITLE
Update to latest version of ngpsql

### ISSUE THREAD

**Issue by idvorkin** [fknx/linqpad-postgresql-driver#26]
I need to use linqpad with redshift.   Support for Redshift is in recent versions of ngpsql, which (I believe) have not been imported into linqpad-postgresql-driver. 

I started making the changes in my [PR](https://github.com/idvorkin/linqpad-postgresql-driver/commits/master), but I don't know how to:
 
1) Run the tests (looks like I need to setup a local DB) 
2) Test in linqpad (do i need to generate a lpx file??) 

I'm happy if you fix, but can make the changes myself with your support.

**Comment by teejay-87** [comment]
1. Honestly, I didn't ever run unit tests. And even more honestly, I needed code to work, not to pass unit tests.
2. No, the main Visual Studio project already copy the necessary files in the correct place:
`xcopy "$(ProjectDir)$(OutDir)*.*" "%LOCALAPPDATA%\LINQPad\Drivers\DataContext\4.6\DynamicLinqPadPostgreSqlDriver (b79463f4d947ddea)\" /y /u`
Once you compiled sources, open (or restart) LinqPad and you will find PostgreSQL (LINQ to DB) driver in the _Add connection_ window.

**Comment by idvorkin** [comment]
:)  on point 1. 

Hymn, when I switched computers, building stopped working (I have LINQPAD_HOME set correctly). I'm getting the error: 

```
c:\gits\flpd\DynamicLinqPadPostgreSqlDriver.sln" (default target) (1) ->
"c:\gits\flpd\DynamicLinqPadPostgreSqlDriver\DynamicLinqPadPostgreSqlDriver.csproj" (default target) (2) ->
"c:\gits\flpd\DynamicLinqPadPostgreSqlDriver.Shared\DynamicLinqPadPostgreSqlDriver.Shared.csproj" (default target) (3:2) ->
(_HandlePackageFileConflicts target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets(30,5): error MSB4018:
The "ResolvePackageFileConflicts" task failed unexpectedly.\r [c:\gits\flpd\DynamicLinqPadPostgreSqlDriver.Shared\DynamicLinqPadPostgreSqlDriver.Shared.csproj]
```

**Comment by teejay-87** [comment]
Sorry for being late.
Honestly, I can't help with your error.

**Comment by fknx** [comment]
Hi, I don't know what is causing the error, but I've updated Npgsql to version `3.2.5`, so feel free to download the newest version of the driver :)

**Comment by idvorkin** [comment]
Hooray - Thanks!!
