### ISSUE TITLE
ConnectionInfo dialog throws an error for users without a password

### ISSUE THREAD

**Issue by henrik-m** [fknx/linqpad-postgresql-driver#4]
The error is only thrown if Integrated Security authentication fails. As it is, it is not possible to perform passwordless authentication with a PostgreSQL user via ConnectionInfo (only with custom connection string).
Possible fix: Only assume "Integrated Security" auth when no username is provided. (see PR)

**Comment by fknx** [comment]
I've merged your fix but I am still getting an `ArgumentNullException` when trying to open a connection without providing a password. This is probably related to issue npgsql/npgsql#942. Can you confirm this behavior?

**Comment by henrik-m** [comment]
Curious... I was able to connect to my Postgres instance using this fix. Will test it again tomorrow with current master.

**Comment by henrik-m** [comment]
I could replicate the `ArgumentNullException (String reference not set to an instance of a String.
Parameter name: s)` on a server which had trust authentication disabled for remote users. This should be handled with a better error message by npgsql. I guess it is indeed related to the ticket you linked.

For my postgres docker image, the exception went away when I changed the following line in `/var/lib/data/postgresql/pg_hba.conf`
```
host all all 0.0.0.0/0 md5
```
to this:
```
host all all 0.0.0.0/0 trust
```

**Comment by fknx** [comment]
Yes I'll close this for now. I've subscribed to the `Npgsql` issue, so I'll verify whether these two issues were related once they release a fix.
