### ISSUE TITLE
InvalidOperationException on fetching associations in LINQPAD results view

### ISSUE THREAD

**Issue by henrik-m** [fknx/linqpad-postgresql-driver#7]
When I issue the following LINQPAD query
```csharp
entities.Take (100)
```
all entities with a one-to-many or many-to-one association to the returned objects fail to load with an InvalidOperationException. This is the StackTrace:
> at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState)
> at Npgsql.NpgsqlCommand.ExecuteDbDataReaderInternal(CommandBehavior behavior)
> at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
> at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
> at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
> at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteReader(Object query)
> at ``LinqToDB.Linq.Query`1.<RunQuery>d__11.MoveNext()``
> at ``LinqToDB.Linq.Query`1.<Map>d__6a.MoveNext()``
> at ``System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)``

The reason for this is that Linq2Db tries to open a DataReader on a connection where there already is an open DataReader. I guess LINQPAD executes something like this to fetch the results and their associations:
```csharp
using (var dataContext = new TypedDataContext("PostgreSQL", "connectionString"))
{
	foreach(var entity in dataContext.entities.Take(100))
	{
		var associatedEntity = entity.manyToOneEntity;
	}
}
```
This fails with the same error because Entity.ResolveOneToMany and Entity.ResolveManyToOne are called in the getter of the association.

A workaround for this is to change the query to `entities.Take (100).ToList()` to close the DataReader before the associations are fetched, but this obviously only fixes the 1st level of association fetching in the results view. One layer down associations still greet us with an InvalidOperationException.

I'm not sure how best to fix this... I guess there would have to be a separate DataConnection for each level of association fetching.

**Comment by fknx** [comment]
Thanks for the detailed analysis. I've changed the `ResolveOneToMany` and `ResolveManyToOne` methods to use a new data context instead of the existing one.

However, the performance can be quite poor when you `Dump` several objects with a lot of associations using the *Rich Text* (and not the *Grid*) output format.

Can you confirm whether this fix solved your issue?

**Comment by henrik-m** [comment]
The original issue is gone, new ones have arisen. They are not a consequence of your fix but merely became visible.

First one:
```
InvalidOperationException {"Nullable object must have a value."}
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , pricesetrule )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DynamicLinqPadPostgreSqlDriver.Entity.ResolveOneToMany[T](String propertyName)
```
This is thrown on a one-to-many relation where the "many"-part is empty.

Second one:
```
AmbiguousMatchException {"Ambiguous match found."}   
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name)
   at DynamicLinqPadPostgreSqlDriver.Entity.PrepareQuery[T](String propertyName)   
```
This happens in 2 cases: 
* A table has more than one column referencing the same table. The entity property names are not derived from the column name but seemingly only from the type name. Therefore they are not unique in this scenario.
* A table has a column referencing itself. In this case a one-to-many and a many-to-one relation property are created with the same name on the entity.

**Comment by fknx** [comment]
I've fixed the naming issue for associations. Now a number is appended to the name until a free property (and field) name is found. I will have to put some work into the naming in the future but this should work for now.

The `InvalidOperationException` occurred when the expression tried to cast a nullable type with a `null` value to the corresponding value type. It should be fixed as well.

**Comment by henrik-m** [comment]
Maybe the property names could be somehow related to the column names? That would make it easier to find the corresponding association for a column as well.

That said, I don't see any errors when I open the rich text view now. Thank you for the work you are putting into this! It is much appreciated.
